tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/test-bot"
tap "github/gh"

# core

brew "mas"
brew "git"
brew "zsh"
brew "tmux"

cask "alacritty"
cask "karabiner-elements"

mas "1Password 7", id: 1333542190

# language related

brew "go"
brew "pyenv"
brew "n" ## until fnm supports arm-based macs
brew "yarn"

# tools

brew "unar"
brew "httpie"
brew "pipx"
brew "github/gh/gh"

cask "docker"
cask "the-unarchiver"

# Apps

cask "visual-studio-code"
cask "google-chrome"


