
theme = "nord"
padding-x = 8
padding-y = [0, 8]

[cursor]
shape = 'Block'

[fonts]
size = 12
family = "Menlo"
extras = [{ family = "Apple Symbols" }, { family = "Apple Color Emoji" }]

[navigation]
mode = "Plain"
