[colors]
foreground = '#ABB2BF'
background = '#282C34'
selection-foreground = '#282C34'
selection-background = '#ABB2BF'
cursor = '#ABB2BF'
black = '3F4451'
red = 'E06C75'
green = '98C379'
yellow = 'D19A66'
blue = '61AFEF'
magenta = 'C678DD'
cyan = '56B6C2'
white = 'D7DAE0'
light_black = '4F5666'
light_red = 'BE5046'
light_green = 'A5E075'
light_yellow = 'E5C07B'
light_blue = '4DC4FF'
light_magenta = 'DE73FF'
light_cyan = '4CD1E0'
light_white = 'E6E6E6'
